### ISSUE TITLE
len(ecog_high_gamma) != len(ecog_raw) * (400/ecog_raw_rate)

### ISSUE THREAD

**Issue by alexanderdfung** [BouchardLab/process_nwb#72]
![ecog_len](https://user-images.githubusercontent.com/46287580/171818346-6be07140-4197-42fc-94a0-1d3666a89bc3.png)
@jthermiz @JesseLivezey In one dataset I'm working with, RVG16_B05, the first number in the above equation is 41344 and the second number is ~41339.06. In another dataset, RVG02_B07, the first number is 60143 and the second is ~60028.88. The starting time in both datasets is listed as 0.0.

**Comment by JesseLivezey** [comment]
Closed by #73
