### ISSUE TITLE
Incorrect documentation for apply_linenoise_notch

### ISSUE THREAD

**Issue by emilyps14** [BouchardLab/process_nwb#8]
The documentation for `apply_linenoise_notch` says that X should have dimensions (n_channels, n_timePoints), but the padding step assumes that the signal has dimensions (n_timePoints,...). So the function works correctly if X is (n_timePoints, n_channels)

**Comment by JesseLivezey** [comment]
Good catch! I updated a bunch of the docstrings in #9. If you run into other unexpected/wrong things, make an issue!

**Comment by emilyps14** [comment]
Thanks, Jesse!
